#########################################################################
# Workflow Name : Maven
# Description : Build, test, and deploy with Apache Maven."
# Version : v3
#########################################################################

name: Maven Reusable Workflow

on:
  workflow_call:
    inputs:
      runsOn:
        description: 'Specifies the runner to be used (e.g., windows-latest, ubuntu-latest)'
        required: true
        type: string
      mavenPomFile:
        description: 'Path to the Maven POM file'
        required: true
        type: string
      options:
        description: 'Additional Maven command-line options'
        required: false
        type: string
        default: ''
      testRunTitle:
        description: 'Title for the test run'
        required: false
        type: string
        default: 'Default Test Run'
      

jobs:
  maven-build:
    runs-on: ${{ inputs.runsOn }}

    steps:
      
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Maven Task Header
        run: |
            # Task Header
            Write-Host "======================================================================="
            Write-Host "Task        : Maven"
            Write-Host "Description : Build, test, and deploy with Apache Maven."
            Write-Host "Version     : v3"
            Write-Host "======================================================================="
        

      # Run Maven commands using PowerShell
      - name: Run Maven Build
        shell: pwsh
        run: |
          Write-Host "Starting Maven Build Process"
          Write-Host "Using POM File: ${{ inputs.mavenPomFile }}"
          Write-Host "Options: ${{ inputs.options }}"
          Write-Host "Test Run Title: ${{ inputs.testRunTitle }}"

      - name: Validate inputs
        shell: pwsh
        run: |
          try {
            $options = ${{ inputs.options }}
            if (-not (Test-Path -Path ${{ inputs.mavenPomFile }})) {
              throw "POM file not found at path: ${{ inputs.mavenPomFile }}"
            }
            if (-not ${{ inputs.testRunTitle }}) {
              throw "Test run title is required but not provided."
            }
            if ($options) {
              Write-Host "Using options: $options"
            }
          } catch {
            Write-Error $_.Exception.Message
            exit 1
          }
 
